### PR TITLE
✨ feat: Add streaming support

### PR DESCRIPTION
**Pull request by wanjohiryan**
This adds:
- [x] Keyboard and mouse handling on the frontend
- [x] Video and audio streaming from the backend to the frontend
- [x] Input server that works with Websockets

Update - 17/11
- [ ] Master docker container to run this
- [ ] Steam runtime
- [ ] Entrypoint.sh

### CODE REVIEW

**Comment by wanjohiryan** [comment]
I just added the first part of handling websockets thru a relay, [partykit](https://github.com/partykit/partykit)

It works locally, i have yet to deploy the server side end of things

FIXME: I think I overwrote the changes done by DatHorse in the prior branch :(
TODO: 
- [ ] Make sure it works with the remote Cloudflare partykit server(s)
- [ ] Test the latency, whether it has improved or dropped

**Comment by wanjohiryan** [comment]
**Update**

- We are using WebRTC for streaming video and audio from the server-side to the client-side. (Yeap, we dropped QUIC)
- We are using WebRTC data channels to share everything else - input, docker commands etc etc

> **NOTE:** No ports were opened during this operation B)

**Comment by wanjohiryan** [comment]
**TODO** 

It has been reported that input has a lot of latency, there might be many causes of this but here's my two cents:
- JSON might be "too heavy" to send, so maybe use ArrayBuffers or protobuf
- We could optimise data-channels to use unordered streams
- Handle input much better in the Golang relay, need to investigate on how many milliseconds we lose there
- Check `nestri-server` and adjust buffers accordingly - need to investigate the latency here as well

**Comment by Blast545** [comment]
@wanjohiryan Can I ask you why QUIC was dropped? I'm just curious, I was taking a look to Rust projects using any kind of moq

**Comment by wanjohiryan** [comment]
Hello 👋🏾  @Blast545 

We dropped MoQ temporarily because it was slowing us down - it is not mature yet.

For example; audio is not working as expected. It is choppy, and when it is not choppy - it is mono channel.

Also, it has very limited support on Firefox and Safari. (Webcodecs and Webtransport have very limited browser support)... WebRTC on the other hand is more widely supported.

I am not against MoQ, and I hope when we get Nestri out of the door, we will come back and help out where we can.

But for now we will be going with the more mature WebRTC

**Comment by Blast545** [comment]
Thanks for your answer! I was getting the same feeling when I tried MoQ a week ago

**Pull request merged**
